version = 1

test_patterns = [
  "**/__tests__/**",
  "**/*.spec.ts",
  "**/*.spec.js",
  "**/*.test.ts",
  "**/*.test.js",
  "**/test_*.py"
]

exclude_patterns = [
  "node_modules",
  "bower_components",
  "out",
  "bin",
  "build",
  "dist",
  "venv"
]

[[analyzers]]
name = "php"

  [analyzers.meta]
  bootstrap_files = [
    "forge-app/bootstrap/app.php"
    ]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "vue",
    "angularjs",
    "react",
    "angular"
  ]
  environment = [
    "nodejs",
    "jquery"
  ]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "standardjs"

[[transformers]]
name = "prettier"

[[transformers]]
name = "php-cs-fixer"
